### PR TITLE
[INCOMPLETE] Add handling of rebar3 deps

### PR DESCRIPTION
**Pull request by waisbrot**
This is not complete; it handles only some of the new deps. There shouldn't be any problems merging it, but I'm posting it here because it helps with debugging related to my #3 PR, not as a real PR itself.

### CODE REVIEW

**Comment by kalidasya** [comment]
this looks promising, what is missing?

**Comment by waisbrot** [comment]
Primarily, it's not tested end-to-end, since I can't get it to work. But I also haven't gone through the rebar3 docs to make sure I've handled all the different cases. I believe `{deps, [foo]}.`  works (get the latest `foo` from hex), for one. And maybe it should verify that you've requested the hex plugin, since otherwise those dependencies will fail.

**Comment by kalidasya** [comment]
So this PR still has the PersistenceException?

**Comment by waisbrot** [comment]
Right, these are the changes needed so that my `rebar.config` is parsable by the plug-in, whereupon I get the PersistenceException.

**Comment by kalidasya** [comment]
I will close this MR because we will drop the Library sensor from the next erlang plugin version. Sorry about that.

**Comment by waisbrot** [comment]
Sounds good!

**Pull request closed without merging**
