### PR TITLE
Upgrade to Sonar 4.5.2

### PR DESCRIPTION
**Pull request by jlrigau**
The goal of this PR is to migrate from Sonar version 4.2 to 4.5.2.

Main features are:

- Refactoring of all the rule classes
- Replacement of ```cardinality = Cardinality.MULTIPLE``` by ```@RuleTemplate```
- Adding of ```@SqaleSubCharacteristic(RulesDefinition.SubCharacteristics.DATA_RELIABILITY)``` and ```@SqaleConstantRemediation("5min")``` on each rule class
- Refactoring of ```RuleRepository``` classes by using ```RulesDefinition```
- Use of ```AnnotationRuleParser```
 and ```RulesDefinitionXmlLoader```
- Refactoring of ```ErlangCommonRulesEngineTest```

### CODE REVIEW

**Comment by jlrigau** [comment]
Right now, all the rule classes are configured with:

```
@SqaleSubCharacteristic(RulesDefinition.SubCharacteristics.DATA_RELIABILITY)
@SqaleConstantRemediation("5min")
```

**Comment by kalidasya** [comment]
@jlrigau can you update your branch?

**Comment by kalidasya** [comment]
@jlrigau can you update the rules based on:
https://github.com/SonarCommunity/sonar-erlang/blob/master/sonar-erlang-plugin/src/main/resources/com/sonar/sqale/erlang-model.xml

they were already configured

**Comment by jlrigau** [comment]
@kalidasya I have configured rule classes with squale information present in https://github.com/SonarCommunity/sonar-erlang/blob/master/sonar-erlang-plugin/src/main/resources/com/sonar/sqale/erlang-model.xml.

I have also removed some deprecated usages.

**Pull request merged**
