### PR TITLE
Upgrade to Sonar 4.2

### PR DESCRIPTION
**Pull request by jlrigau**
The goal of this PR is to migrate from Sonar version 3.7 to 4.2.

Main features are:

- Removing of ```ErlangSourceImporter```
- Replacing of ```ModuleFileSystem``` by ```FileSystem```
- Use of ```FilePredicate``` with ```InputFile``` instead of ```FileQuery```
- Refactoring of ```ProjectUtil``` test class
- Use of ```DefaultFileSystem``` in test classes instead of a mock filesystem

### CODE REVIEW

**Comment by kalidasya** [comment]
@dgageot can you check why the IT tests are failing on DEV and LTS?

**Comment by kalidasya** [comment]
@jlrigau it looks good, thanks for the MR, I will wait a bit maybe @dgageot can says something about the travis failure

**Comment by dgageot** [comment]
ping @sns-seb Maybe you can take a look at the ITs. Thanks

**Comment by jlrigau** [comment]
@dgageot @sns-seb Is there a way to run ITs on a local machine?

**Comment by dbolkensteyn** [comment]
@jlrigau Yes you can - but it's going to be a bit painful (we're working on improving that):

1. Build sonar-erlang locally
2. Copy the following closed source artifacts into your own local maven repository: https://github.com/SonarSource/travis-utils/tree/master/m2repo
3. Set the `TRAVIS` environment variable to value - doesn't matter what
4. Go into the its\plugin folder, and run the integration test command:

```
mvn clean install -DerlangVersion="DEV" -Dsonar.runtimeVersion="LTS_OR_OLDEST_COMPATIBLE" -Dmaven.test.redirectTestOutputToFile=false -Dsonar.jdbc.dialect="embedded" -Dorchestrator.updateCenterUrl="http://update.sonarsource.org/update-center-dev.properties" -Dmaven.localRepository="[**path to your local .m2/repository folder**]"
```

**Comment by jlrigau** [comment]
@dbolkensteyn Thanks for the tips but I have still an error with the ochestrator builder:

```
Running com.sonar.it.erlang.ErlangTestSuite
14:20:06.853 WARN  Nexus remote repository url is not set. Please define maven.nexusUrl
14:20:06.870 INFO  Downloading: http://update.sonarsource.org/update-center-dev.properties
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.134 sec <<< FAILURE! - in com.sonar.it.erlang.ErlangTestSuite
com.sonar.it.erlang.ErlangTestSuite  Time elapsed: 1.132 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
	at com.sonar.orchestrator.OrchestratorBuilder.resolvePluginVersion(OrchestratorBuilder.java:146)
	at com.sonar.orchestrator.OrchestratorBuilder.getPluginRelease(OrchestratorBuilder.java:127)
	at com.sonar.orchestrator.OrchestratorBuilder.getPluginVersion(OrchestratorBuilder.java:109)
	at com.sonar.orchestrator.OrchestratorBuilder.addPlugin(OrchestratorBuilder.java:221)
	at com.sonar.it.erlang.ErlangTestSuite.initOrchestrator(ErlangTestSuite.java:46)
	at com.sonar.it.erlang.ErlangTestSuite.<clinit>(ErlangTestSuite.java:41)
```

**Comment by dbolkensteyn** [comment]
@jlrigau you're right - and it actually is failing for the same reason on my box. The root cause is identified - but I need some time to make the proper fix.

**Comment by dbolkensteyn** [comment]
@jlrigau You know should be able to run ITs on your machine, with the following last command:
```
mvn clean install -Dsonar.runtimeVersion="LTS" -Dmaven.test.redirectTestOutputToFile=false -Dsonar.jdbc.dialect="embedded" -Dorchestrator.updateCenterUrl="http://update.sonarsource.org/update-center-dev.properties" -Dmaven.localRepository="[**path to your local .m2/repository folder**]"
```

This will test the `sonar-erlang-plugin.jar` file built locally, finding it with a relate path and not via the the Maven local repository.

**Comment by jlrigau** [comment]
@dbolkensteyn where I have to put the ```sonar-erlang-plugin.jar```` file?

**Comment by dbolkensteyn** [comment]
you don't have to move it manually @jlrigau - see this commit: https://github.com/SonarCommunity/sonar-erlang/commit/7152a56c85af32facccb42f7ec8fe09e307fe6a7

**Comment by jlrigau** [comment]
@dbolkensteyn I have still an issue with the orchestrator builer:

```
Running com.sonar.it.erlang.ErlangTestSuite
11:49:46.500 WARN  Nexus remote repository url is not set. Please define maven.nexusUrl
11:49:46.528 INFO  Downloading: file:/Users/jlrigau/Work/repository
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.466 sec <<< FAILURE! - in com.sonar.it.erlang.ErlangTestSuite
com.sonar.it.erlang.ErlangTestSuite  Time elapsed: 0.464 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
	at org.sonar.updatecenter.common.UpdateCenterDeserializer.reportError(UpdateCenterDeserializer.java:167)
	at org.sonar.updatecenter.common.UpdateCenterDeserializer.reportUndefined(UpdateCenterDeserializer.java:409)
	at org.sonar.updatecenter.common.UpdateCenterDeserializer.get(UpdateCenterDeserializer.java:415)
	at org.sonar.updatecenter.common.UpdateCenterDeserializer.parseSonarDevVersions(UpdateCenterDeserializer.java:273)
	at org.sonar.updatecenter.common.UpdateCenterDeserializer.parseSonar(UpdateCenterDeserializer.java:267)
	at org.sonar.updatecenter.common.UpdateCenterDeserializer.fromProperties(UpdateCenterDeserializer.java:137)
	at org.sonar.updatecenter.common.UpdateCenterDeserializer.fromSingleFile(UpdateCenterDeserializer.java:106)
	at com.sonar.orchestrator.OrchestratorBuilder.getUpdateCenter(OrchestratorBuilder.java:157)
	at com.sonar.orchestrator.OrchestratorBuilder.getSonarVersion(OrchestratorBuilder.java:83)
	at com.sonar.orchestrator.OrchestratorBuilder.build(OrchestratorBuilder.java:338)
	at com.sonar.it.erlang.ErlangTestSuite.initOrchestrator(ErlangTestSuite.java:50)
	at com.sonar.it.erlang.ErlangTestSuite.<clinit>(ErlangTestSuite.java:41)
```

**Comment by dbolkensteyn** [comment]
do you still face that issue @jlrigau ? I've not encountered that one myself - perhaps it was temporary

**Comment by jlrigau** [comment]
@dbolkensteyn it works on my machine, thanks for your help :)

**Comment by dgageot** [comment]
Is it something that needs to be fixed in the test then? Flaky test?

**Comment by kalidasya** [comment]
@dgageot it seems the tests are flaky, no clue why

**Comment by kalidasya** [comment]
@jlrigau sorry, can you update the branch? Ive removed the library sensor

**Comment by jlrigau** [comment]
@kalidasya yes sure

**Comment by jlrigau** [comment]
I have fixed the test failure due to a misuse of ```org.sonar.api.resources.File.create()``` with ```org.sonar.api.batch.fs.FileSystem``` and ```org.sonar.api.batch.fs.FilePredicate```.

**Pull request merged**
