### PR TITLE
Improve Erlang grammar

### PR DESCRIPTION
**Pull request by jlrigau**
Two macro improvements to implement:

- Bit size with function
- Macro with record field

### CODE REVIEW

**Comment by dbolkensteyn** [comment]
Please don't merge until Travis ITs are back - I'll fix them tomorrow.

**Comment by dbolkensteyn** [comment]
@jlrigau looks like a parser unit test is now failing

**Comment by kalidasya** [comment]
@jlrigau maybe its me, but I do not see any improvement in the erlang grammar, or you just reporting the failing usecases?

**Comment by kalidasya** [comment]
@jlrigau just re-read the MR message, I turn this into an issue

**Comment by jlrigau** [comment]
@kalidasya Thanks for having created these 2 issues

**Pull request closed without merging**
